#! /bin/bash

CC=g++

PROJECT=`pwd`
PROJECT=${PROJECT##*/}
echo Making $PROJECT =================================================

PROTON=/home/mick/proton

FLAGS="-pedantic"
DEFS=
OPTO=-O3

for file in *.c
do
  echo compiling $file --------------------------------------------
  $CC                                  \
    $FLAGS                             \
    -I${PROTON}/proton-c               \
    $DEFS                              \
    $OPTO                              \
    -c                                 \
    $file
done

echo Linking ====================================================

$CC                           \
  -L/usr/lib64                \
  -o $PROJECT                 \
  $PROJECT.o                  \
  -lqpid-proton

rm *.o

echo -e "Done ================================\n\n\n\n"


