#! /bin/bash

./psend                      \
  --host            0.0.0.0  \
  --port            5673     \
  --messages        1000000  \
  --message_length  100      \
  --n_links         5        \
  --output          stderr

